### ISSUE TITLE
0.1.22 produce nothing and fail silently with nodejs

### ISSUE THREAD

**Issue by HugoPoi** [JuanIrache/gpmf-extract#41]
Very weird but the changes introduce in https://github.com/JuanIrache/gpmf-extract/compare/v0.1.21...v0.1.22 produce nothing, the extract start but stop just before the end of the file, and nodejs exit without any error or warning.

nodejs version `v15.6.0`

## Sample of code for reproducing
```javascript
const res = await gpmfExtract(bufferAppender(options.input, 10 * 1024 * 1024));

  function bufferAppender(path, chunkSize) {
    return function (mp4boxFile) {
      console.log('SETUP STREAM');
      var stream = fs.createReadStream(path, { highWaterMark: chunkSize });
      var bytesRead = 0;
      stream.on('end', () => {
        mp4boxFile.flush();
      });
      stream.on('data', chunk => {
        var arrayBuffer = new Uint8Array(chunk).buffer;
        arrayBuffer.fileStart = bytesRead;
        mp4boxFile.appendBuffer(arrayBuffer);
        bytesRead += chunk.length;
        console.log('progress bytesRead', bytesRead);
      });
      stream.on('error', error => {
         console.error(error);
      });
      stream.resume();
    };
  }

```

**Comment by JuanIrache** [comment]
Thanks for the heads-up, Hugo.

Are you able to test if the culprit is

` mp4boxFile = MP4Box.createFile(false);
` 
 ?

Removing the false was breaking the progress bar in the browser. We can maybe add it conditionally depending on the environment.

Otherwise it's this loop, which seems to only be necessary in the browser as well, so it's manageable too.

`for (var i = 0; i < sample.size; i++) {
` 
 Otherwise I will test it myself when I find a moment.
 
 Thanks

**Comment by willprice** [comment]
If I remove `false` from `MP4Box.createFile(false)` then things work as expected
