### ISSUE TITLE
enable processing to be cancelled

### ISSUE THREAD

**Issue by gunta987** [JuanIrache/gpmf-extract#49]
If processing a large file, it can take a long time and the user may wish to cancel in that time. Additionally, I have come across a scenario where a video I've been supplied throws an error in mp4box that doesn't cancel the process, and progress goes above 100% without ever finishing (I allowed it to get to >800% before refreshing the page, meanwhile CPU usage is 100%). If running using webWorkers, throwing an Error from the progress function doesn't stop the process either.

Can you please enable functionality to pass in a cancellation token in options?

**Comment by JuanIrache** [comment]
Hi. Thank you for raising these issues. They are valid points.

Are you able to share the file that is going beyond 100%, for testing?

If you have a chance to start implementing these improvements, feel free to
send pull requests. Otherwise I will work on them when I find the time.

**Comment by gunta987** [comment]
Thanks. I've made the video available at https://1drv.ms/u/s!At523gPWXcusgQMPo3Peix57UjS0?e=mUfEat 

This video is clearly corrupted, since it won't even open in VLC, but the extractor does recognise it as a GoPro file and attempts to extract telemetry. I have also tried the file at https://goprotelemetryextractor.com/free/ and get the same results (extraction process never ends)

**Comment by JuanIrache** [comment]
Thank you for the sample file. I made two changes:

- Error handling was completely broken within the readBlock files. Should be better now (but the error with that specific file seems hard to handle in a more elegant way. See below)
- If the progress goes beyond 200% the file is rejected. I set a generous margin because in the past files were doing weird things with the progress, so I wouldn't want to cancel something that will succeed even if it's over 100%. There could be better solutions.

The crash itself comes from mp4box and I have no direct control over it, nor the knowledge or time to improve that within mp4box at the moment. If you make additional findings about that, please let me know.

Adding the cancel function will require a bigger refactor, so I'm not sure when/if I'll be able to work on that. PRs in that direction are welcome.

**Comment by gunta987** [comment]
Easy enough to implement for browserMode, because the data is read in chunks.

I'm new to github: how do I create a PR when I can't push a branch to this repo?

**Comment by JuanIrache** [comment]
You can fork the project, make your changes and then send the PR request to
the dev branch. There must be good tutorials about this, but in any case if
you get it working on your fork of the repo I can just copy the changes.

Juan Irache
Independent Software Developer
https://prototyping.barcelona

**Comment by gunta987** [comment]
Hi Juan,

I notice that you changed resolve(null) to reject('Canceled by user'). All good, but the documentation needs updating as I wrote it to reflect resolving with null.

**Comment by JuanIrache** [comment]
Good catch
